import { StyleSheet } from "react-native";

export const CalendarPickerModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 34,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: "#d1d0cd",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 17,
    fontWeight: "600",
    color: "#323130",
    textAlign: "center",
    marginBottom: 16,
  },
  calendarContainer: {
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  navButton: { padding: 8 },
  navText: { fontSize: 28, color: "#0078d4", fontWeight: "300" },
  monthYear: { fontSize: 17, fontWeight: "600", color: "#323130" },
  daysHeader: {
    flexDirection: "row",
    marginBottom: 8,
  },
  dayHeader: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
  },
  dayHeaderText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#605e5c",
  },
  daysGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  dayCell: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCellOtherMonth: { opacity: 0.3 },
  dayCellToday: { backgroundColor: "#f0f7ff", borderRadius: 20 },
  dayCellSelected: { backgroundColor: "#0078d4", borderRadius: 20 },
  dayText: { fontSize: 16, color: "#323130" },
  dayTextOtherMonth: { color: "#a19f9d" },
  dayTextToday: { color: "#0078d4", fontWeight: "600" },
  dayTextSelected: { color: "#fff", fontWeight: "600" },
  timeSection: {
    paddingHorizontal: 20,
    marginTop: 12,
  },
  timeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  timeLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#323130",
  },
  timeDisplay: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  timeText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0078d4",
  },
  removeTimeText: {
    fontSize: 14,
    color: "#d13438",
  },
  setTimeButton: {
    paddingVertical: 6,
    paddingHorizontal: 16,
    backgroundColor: "#f0f7ff",
    borderRadius: 8,
  },
  setTimeText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0078d4",
  },
  timePickerContainer: {
    marginTop: 8,
    alignItems: "center",
  },
  preview: {
    alignItems: "center",
    paddingVertical: 16,
    backgroundColor: "#f8f9fa",
    marginHorizontal: 20,
    borderRadius: 8,
    marginTop: 16,
  },
  previewLabel: { fontSize: 12, color: "#605e5c", marginBottom: 4 },
  previewDate: {
    fontSize: 15,
    fontWeight: "600",
    color: "#0078d4",
  },
  buttons: {
    flexDirection: "row",
    marginTop: 20,
    marginHorizontal: 20,
    gap: 12,
  },
  clearButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: "#f3f2f1",
  },
  clearText: { fontSize: 16, fontWeight: "600", color: "#d13438" },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#f3f2f1",
    alignItems: "center",
  },
  cancelText: { fontSize: 16, fontWeight: "600", color: "#605e5c" },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#0078d4",
    alignItems: "center",
  },
  saveText: { fontSize: 16, fontWeight: "600", color: "#fff" },
});