import {StyleSheet} from "react-native";

export const reminderModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 34,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: "#d1d0cd",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 17,
    fontWeight: "600",
    color: "#323130",
    textAlign: "center",
    marginBottom: 16,
  },
  optionsList: { maxHeight: 350 },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f2f1",
  },
  optionSelected: { backgroundColor: "#e1f3ff" },
  optionContent: { flex: 1 },
  optionText: { fontSize: 16, color: "#323130" },
  optionTextSelected: { color: "#0078d4", fontWeight: "600" },
  optionDescription: { fontSize: 12, color: "#605e5c", marginTop: 2 },
  checkmark: { fontSize: 18, color: "#0078d4" },
  customPickerContainer: {
    paddingVertical: 12,
    alignItems: "center",
  },
  preview: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: "#f8f9fa",
    marginHorizontal: 20,
    borderRadius: 8,
    marginTop: 16,
  },
  previewLabel: { fontSize: 14, color: "#605e5c", marginRight: 8 },
  previewDate: { fontSize: 14, fontWeight: "600", color: "#0078d4" },
  buttons: {
    flexDirection: "row",
    marginTop: 20,
    marginHorizontal: 20,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#f3f2f1",
    alignItems: "center",
  },
  cancelText: { fontSize: 16, fontWeight: "600", color: "#605e5c" },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#0078d4",
    alignItems: "center",
  },
  saveText: { fontSize: 16, fontWeight: "600", color: "#fff" },
});