import { StyleSheet } from "react-native";

export const RepeatModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 34,
    maxHeight: "90%",
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: "#d1d0cd",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 17,
    fontWeight: "600",
    color: "#323130",
    textAlign: "center",
    marginBottom: 16,
  },
  optionsList: { maxHeight: 500 },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f2f1",
  },
  optionSelected: { backgroundColor: "#e1f3ff" },
  optionText: { fontSize: 16, color: "#323130" },
  optionTextSelected: { color: "#0078d4", fontWeight: "600" },
  timeHint: { fontSize: 14, color: "#605e5c" },
  checkmark: { fontSize: 18, color: "#0078d4" },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#605e5c",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  // Weekly
  dayPickerContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f2f1",
  },
  dayRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 12,
  },
  dayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f2f1",
  },
  dayButtonSelected: {
    backgroundColor: "#0078d4",
  },
  dayButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#323130",
  },
  dayButtonTextSelected: {
    color: "#fff",
  },
  // Monthly
  monthlyContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f2f1",
  },
  monthlyOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  monthlyOptionSelected: {
    backgroundColor: "#e1f3ff",
  },
  monthlyOptionText: {
    fontSize: 15,
    color: "#323130",
  },
  dayNumberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dayArrow: {
    fontSize: 22,
    color: "#0078d4",
    fontWeight: "600",
    paddingHorizontal: 8,
  },
  dayNumber: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0078d4",
    minWidth: 24,
    textAlign: "center",
  },
  // End Repeat
  endRepeatContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f2f1",
  },
  endRepeatOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  endDatePicker: {
    paddingHorizontal: 20,
    marginTop: 8,
  },
  endDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 8,
  },
  endDateValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0078d4",
    minWidth: 120,
    textAlign: "center",
  },
  endDateHint: {
    fontSize: 14,
    color: "#605e5c",
  },
  endDateArrow: {
    padding: 4,
  },
  preview: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: "#f8f9fa",
    marginHorizontal: 20,
    borderRadius: 8,
    marginTop: 16,
  },
  previewLabel: { fontSize: 14, color: "#605e5c", marginRight: 8 },
  previewDate: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0078d4",
    textAlign: "center",
  },
  buttons: {
    flexDirection: "row",
    marginTop: 20,
    marginHorizontal: 20,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#f3f2f1",
    alignItems: "center",
  },
  cancelText: { fontSize: 16, fontWeight: "600", color: "#605e5c" },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#0078d4",
    alignItems: "center",
  },
  saveText: { fontSize: 16, fontWeight: "600", color: "#fff" },
});
